default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: <%= ENV['POSTGRESQL_PORT'] || 5432 %>
  username: <%= ENV['POSTGRESQL_USER'] || 'papu' %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] || 'papu' %>

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  <<: *default
  database: papu_prod
