default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: papu
  password: papu

development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: papu
  password: papu
  database: papu_dev

test:
  «: *default
  database: db_test

production:
  «: *default
  database: db_name
