require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ContratacionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Contratacion. As you add validations to Contratacion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContratacionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all contratacions as @contratacions" do
      contratacion = Contratacion.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:contratacions)).to eq([contratacion])
    end
  end

  describe "GET #show" do
    it "assigns the requested contratacion as @contratacion" do
      contratacion = Contratacion.create! valid_attributes
      get :show, {:id => contratacion.to_param}, valid_session
      expect(assigns(:contratacion)).to eq(contratacion)
    end
  end

  describe "GET #new" do
    login_admin
    it "assigns a new contratacion as @contratacion" do
      get :new, {}, valid_session
      expect(assigns(:contratacion)).to be_a_new(Contratacion)
    end
  end

  describe "GET #edit" do
    login_admin
    it "assigns the requested contratacion as @contratacion" do
      contratacion = Contratacion.create! valid_attributes
      get :edit, {:id => contratacion.to_param}, valid_session
      expect(assigns(:contratacion)).to eq(contratacion)
    end
  end

  describe "POST #create" do
    login_admin
    context "with valid params" do
      it "creates a new Contratacion" do
        expect {
          post :create, {:contratacion => valid_attributes}, valid_session
        }.to change(Contratacion, :count).by(1)
      end

      it "assigns a newly created contratacion as @contratacion" do
        post :create, {:contratacion => valid_attributes}, valid_session
        expect(assigns(:contratacion)).to be_a(Contratacion)
        expect(assigns(:contratacion)).to be_persisted
      end

      it "redirects to the created contratacion" do
        post :create, {:contratacion => valid_attributes}, valid_session
        expect(response).to redirect_to(Contratacion.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved contratacion as @contratacion" do
        post :create, {:contratacion => invalid_attributes}, valid_session
        expect(assigns(:contratacion)).to be_a_new(Contratacion)
      end

      it "re-renders the 'new' template" do
        post :create, {:contratacion => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    login_admin
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contratacion" do
        contratacion = Contratacion.create! valid_attributes
        put :update, {:id => contratacion.to_param, :contratacion => new_attributes}, valid_session
        contratacion.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested contratacion as @contratacion" do
        contratacion = Contratacion.create! valid_attributes
        put :update, {:id => contratacion.to_param, :contratacion => valid_attributes}, valid_session
        expect(assigns(:contratacion)).to eq(contratacion)
      end

      it "redirects to the contratacion" do
        contratacion = Contratacion.create! valid_attributes
        put :update, {:id => contratacion.to_param, :contratacion => valid_attributes}, valid_session
        expect(response).to redirect_to(contratacion)
      end
    end

    context "with invalid params" do
      it "assigns the contratacion as @contratacion" do
        contratacion = Contratacion.create! valid_attributes
        put :update, {:id => contratacion.to_param, :contratacion => invalid_attributes}, valid_session
        expect(assigns(:contratacion)).to eq(contratacion)
      end

      it "re-renders the 'edit' template" do
        contratacion = Contratacion.create! valid_attributes
        put :update, {:id => contratacion.to_param, :contratacion => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    login_admin
    it "destroys the requested contratacion" do
      contratacion = Contratacion.create! valid_attributes
      expect {
        delete :destroy, {:id => contratacion.to_param}, valid_session
      }.to change(Contratacion, :count).by(-1)
    end

    it "redirects to the contratacions list" do
      contratacion = Contratacion.create! valid_attributes
      delete :destroy, {:id => contratacion.to_param}, valid_session
      expect(response).to redirect_to(contratacions_url)
    end
  end

end
