require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EleccionInternasController, type: :controller do
  include Devise::TestHelpers
  # This should return the minimal set of attributes required to create a valid
  # EleccionInterna. As you add validations to EleccionInterna, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EleccionInternasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all eleccion_internas as @eleccion_internas" do
      eleccion_interna = EleccionInterna.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:eleccion_internas)).to eq([eleccion_interna])
    end
  end

  describe "GET #show" do
    it "assigns the requested eleccion_interna as @eleccion_interna" do
      eleccion_interna = EleccionInterna.create! valid_attributes
      get :show, {:id => eleccion_interna.to_param}, valid_session
      expect(assigns(:eleccion_interna)).to eq(eleccion_interna)
    end
  end

  describe "GET #new" do
    it "assigns a new eleccion_interna as @eleccion_interna" do
      get :new, {}, valid_session
      expect(assigns(:eleccion_interna)).to be_a_new(EleccionInterna)
    end
  end

  describe "GET #edit" do
    it "assigns the requested eleccion_interna as @eleccion_interna" do
      eleccion_interna = EleccionInterna.create! valid_attributes
      get :edit, {:id => eleccion_interna.to_param}, valid_session
      expect(assigns(:eleccion_interna)).to eq(eleccion_interna)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new EleccionInterna" do
        expect {
          post :create, {:eleccion_interna => valid_attributes}, valid_session
        }.to change(EleccionInterna, :count).by(1)
      end

      it "assigns a newly created eleccion_interna as @eleccion_interna" do
        post :create, {:eleccion_interna => valid_attributes}, valid_session
        expect(assigns(:eleccion_interna)).to be_a(EleccionInterna)
        expect(assigns(:eleccion_interna)).to be_persisted
      end

      it "redirects to the created eleccion_interna" do
        post :create, {:eleccion_interna => valid_attributes}, valid_session
        expect(response).to redirect_to(EleccionInterna.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved eleccion_interna as @eleccion_interna" do
        post :create, {:eleccion_interna => invalid_attributes}, valid_session
        expect(assigns(:eleccion_interna)).to be_a_new(EleccionInterna)
      end

      it "re-renders the 'new' template" do
        post :create, {:eleccion_interna => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested eleccion_interna" do
        eleccion_interna = EleccionInterna.create! valid_attributes
        put :update, {:id => eleccion_interna.to_param, :eleccion_interna => new_attributes}, valid_session
        eleccion_interna.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested eleccion_interna as @eleccion_interna" do
        eleccion_interna = EleccionInterna.create! valid_attributes
        put :update, {:id => eleccion_interna.to_param, :eleccion_interna => valid_attributes}, valid_session
        expect(assigns(:eleccion_interna)).to eq(eleccion_interna)
      end

      it "redirects to the eleccion_interna" do
        eleccion_interna = EleccionInterna.create! valid_attributes
        put :update, {:id => eleccion_interna.to_param, :eleccion_interna => valid_attributes}, valid_session
        expect(response).to redirect_to(eleccion_interna)
      end
    end

    context "with invalid params" do
      it "assigns the eleccion_interna as @eleccion_interna" do
        eleccion_interna = EleccionInterna.create! valid_attributes
        put :update, {:id => eleccion_interna.to_param, :eleccion_interna => invalid_attributes}, valid_session
        expect(assigns(:eleccion_interna)).to eq(eleccion_interna)
      end

      it "re-renders the 'edit' template" do
        eleccion_interna = EleccionInterna.create! valid_attributes
        put :update, {:id => eleccion_interna.to_param, :eleccion_interna => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested eleccion_interna" do
      eleccion_interna = EleccionInterna.create! valid_attributes
      expect {
        delete :destroy, {:id => eleccion_interna.to_param}, valid_session
      }.to change(EleccionInterna, :count).by(-1)
    end

    it "redirects to the eleccion_internas list" do
      eleccion_interna = EleccionInterna.create! valid_attributes
      delete :destroy, {:id => eleccion_interna.to_param}, valid_session
      expect(response).to redirect_to(eleccion_internas_url)
    end
  end

end
