require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MarcoInternosController, type: :controller do
  include Devise::TestHelpers
  # This should return the minimal set of attributes required to create a valid
  # MarcoInterno. As you add validations to MarcoInterno, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MarcoInternosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all marco_internos as @marco_internos" do
      marco_interno = MarcoInterno.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:marco_internos)).to eq([marco_interno])
    end
  end

  describe "GET #show" do
    it "assigns the requested marco_interno as @marco_interno" do
      marco_interno = MarcoInterno.create! valid_attributes
      get :show, {:id => marco_interno.to_param}, valid_session
      expect(assigns(:marco_interno)).to eq(marco_interno)
    end
  end

  describe "GET #new" do
    it "assigns a new marco_interno as @marco_interno" do
      get :new, {}, valid_session
      expect(assigns(:marco_interno)).to be_a_new(MarcoInterno)
    end
  end

  describe "GET #edit" do
    it "assigns the requested marco_interno as @marco_interno" do
      marco_interno = MarcoInterno.create! valid_attributes
      get :edit, {:id => marco_interno.to_param}, valid_session
      expect(assigns(:marco_interno)).to eq(marco_interno)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MarcoInterno" do
        expect {
          post :create, {:marco_interno => valid_attributes}, valid_session
        }.to change(MarcoInterno, :count).by(1)
      end

      it "assigns a newly created marco_interno as @marco_interno" do
        post :create, {:marco_interno => valid_attributes}, valid_session
        expect(assigns(:marco_interno)).to be_a(MarcoInterno)
        expect(assigns(:marco_interno)).to be_persisted
      end

      it "redirects to the created marco_interno" do
        post :create, {:marco_interno => valid_attributes}, valid_session
        expect(response).to redirect_to(MarcoInterno.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved marco_interno as @marco_interno" do
        post :create, {:marco_interno => invalid_attributes}, valid_session
        expect(assigns(:marco_interno)).to be_a_new(MarcoInterno)
      end

      it "re-renders the 'new' template" do
        post :create, {:marco_interno => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested marco_interno" do
        marco_interno = MarcoInterno.create! valid_attributes
        put :update, {:id => marco_interno.to_param, :marco_interno => new_attributes}, valid_session
        marco_interno.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested marco_interno as @marco_interno" do
        marco_interno = MarcoInterno.create! valid_attributes
        put :update, {:id => marco_interno.to_param, :marco_interno => valid_attributes}, valid_session
        expect(assigns(:marco_interno)).to eq(marco_interno)
      end

      it "redirects to the marco_interno" do
        marco_interno = MarcoInterno.create! valid_attributes
        put :update, {:id => marco_interno.to_param, :marco_interno => valid_attributes}, valid_session
        expect(response).to redirect_to(marco_interno)
      end
    end

    context "with invalid params" do
      it "assigns the marco_interno as @marco_interno" do
        marco_interno = MarcoInterno.create! valid_attributes
        put :update, {:id => marco_interno.to_param, :marco_interno => invalid_attributes}, valid_session
        expect(assigns(:marco_interno)).to eq(marco_interno)
      end

      it "re-renders the 'edit' template" do
        marco_interno = MarcoInterno.create! valid_attributes
        put :update, {:id => marco_interno.to_param, :marco_interno => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested marco_interno" do
      marco_interno = MarcoInterno.create! valid_attributes
      expect {
        delete :destroy, {:id => marco_interno.to_param}, valid_session
      }.to change(MarcoInterno, :count).by(-1)
    end

    it "redirects to the marco_internos list" do
      marco_interno = MarcoInterno.create! valid_attributes
      delete :destroy, {:id => marco_interno.to_param}, valid_session
      expect(response).to redirect_to(marco_internos_url)
    end
  end

end
